production:
  adapter: postgresql
  encoding: utf8
  database: filmacos_production
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/db.sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  host: 127.0.0.1